package pe.edu.utp.tmo.service;
import static org.junit.jupiter.api.Assertions.*; import static org.mockito.ArgumentMatchers.*; import static org.mockito.Mockito.*; import java.time.*; import java.util.*; import org.junit.jupiter.api.*; import org.junit.jupiter.api.extension.ExtendWith; import org.mockito.*; import org.mockito.junit.jupiter.MockitoExtension; import pe.edu.utp.tmo.dao.*; import pe.edu.utp.tmo.dto.request.TicketCloseRequest; import pe.edu.utp.tmo.exception.*; import pe.edu.utp.tmo.mapper.TicketMapper; import pe.edu.utp.tmo.model.entity.*; import pe.edu.utp.tmo.model.enums.*; import pe.edu.utp.tmo.service.impl.TicketServiceImpl; import pe.edu.utp.tmo.util.*;
@ExtendWith(MockitoExtension.class)
class TicketServiceImplTest {
 @Mock UsuarioDAO usuarios; @Mock CasoDAO casos; @Mock RegistroTMODAO registros; @Mock TipificacionDAO tips; @Mock AuditoriaDAO auditoria;
 TicketServiceImpl service; Usuario analista; Clock fixed;
 @BeforeEach void setup(){ fixed=Clock.fixed(Instant.parse("2026-06-10T13:00:00Z"),ZoneOffset.UTC); service=new TicketServiceImpl(usuarios,casos,registros,tips,auditoria,new TmoCalculator(),new TicketCodeGenerator(fixed),new TicketMapper(),fixed); analista=new Usuario("Analista","analista@tmo.local","hash",RolUsuario.ANALISTA,"Back Office",true); }
 @Test void noCierraSinTipificacion(){ Caso c=Caso.prueba(10L,analista,LocalDateTime.of(2026,6,10,12,50)); when(usuarios.buscarPorCorreo("analista@tmo.local")).thenReturn(Optional.of(analista)); when(casos.buscarPorId(10L)).thenReturn(Optional.of(c)); assertThrows(ValidacionNegocioException.class,()->service.cerrarTicket("analista@tmo.local",10L,new TicketCloseRequest(1L,"Gestión realizada correctamente"))); verify(registros,never()).guardar(any()); }
 @Test void noCierraSinObservacionValida(){ Caso c=Caso.prueba(10L,analista,LocalDateTime.of(2026,6,10,12,50)); when(usuarios.buscarPorCorreo("analista@tmo.local")).thenReturn(Optional.of(analista)); when(casos.buscarPorId(10L)).thenReturn(Optional.of(c)); when(tips.buscarPorId(1L)).thenReturn(Optional.of(new Tipificacion("Gestión completada",true))); assertThrows(ValidacionNegocioException.class,()->service.cerrarTicket("analista@tmo.local",10L,new TicketCloseRequest(1L,"ok"))); verify(registros,never()).guardar(any()); }
 @Test void noCierraTicketCerrado(){ Caso c=Caso.prueba(10L,analista,LocalDateTime.of(2026,6,10,12,50)); c.cerrar(new Tipificacion("Gestión completada",true),"Gestión realizada correctamente",LocalDateTime.of(2026,6,10,12,55)); when(usuarios.buscarPorCorreo("analista@tmo.local")).thenReturn(Optional.of(analista)); when(casos.buscarPorId(10L)).thenReturn(Optional.of(c)); assertThrows(TicketNoCerrableException.class,()->service.cerrarTicket("analista@tmo.local",10L,new TicketCloseRequest(1L,"Gestión realizada correctamente"))); }
}
